[package]
name = "iroh_test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"
path = "src/client/main.rs"

[[bin]]
name = "server"
path = "src/server/main.rs"

[dependencies]
anyhow = "1.0.95"
iroh = "0.30.0"
tokio = { version = "1.42.0", features = ["time"] }
