[package]
name = "iroh_test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"
path = "src/client/main.rs"

[[bin]]
name = "server"
path = "src/server/main.rs"

[dependencies]
anyhow = "1.0.95"
iroh = "0.30.0"
rmp-serde = "1.3.0"
serde = "1.0.217"
serde_json = "1.0.134"
tokio = { version = "1.42.0", features = ["time"] }
